# !/bin/bash

if [ "$#" -ne 10 ] && [ "$#" -ne 8 ] && [ "$#" -ne 12 ] ; then
    echo "Invalid Arguments"
    echo "Usage: script requires 3-5 Arguments: "
    echo "       -s Path to folder which contains following scripts with exact names:"
    echo "                   StandardForm.XXX, ParityCheck.XXX, DecodingTable.XXX, Encode.XXX Decode.xxx"
    echo "       -t Path to folder which contains public tests(where A,B,C,D,E folders are located)"
    echo "       -T Path to folder which contains test scriptis (i.e. test_A.py, test_B.py"
    echo "       -r Path to folder where we should put output for each test"
    echo "       -e Extension of your file (pass with dot exaple: .py)"
    echo "       -i Your Interpreter (If using executable leave empty for example: if generated by gcc)"
    echo "Example: ./hw3_checker.sh -s src/ -t public_tests/ -r res/ -e .py -i python3 -T script/"
    exit
fi
# Read Command Line Arguments
POSITIONAL=()
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        -s)
            SCRIPT_FOLDER_PATH="$2"
            shift # past argument
            shift # past value
        ;;
        -t)
            TEST_FOLDER_PATH="$2"
            shift # past argument
            shift # past value
        ;;
        -T)
            TESTER_SCRIPT_FOLDER="$2"
            shift # past argument
            shift # past value
        ;;
        -r)
            RESULT_DIR_NAME="$2"
            shift # past argument
            shift # past value
        ;;
        -e)
            EXTENSION="$2"
            shift # past argument
            shift # past value
        ;;
        -i)
            INTERPRETER="$2"
            shift # past argument
            shift # past value
        ;;
        *)    # unknown option
            POSITIONAL+=("$1") # save it in an array for later
            shift # past argument
        ;;
    esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters


[ -z "$SCRIPT_FOLDER_PATH" ] && printf "Script Folder path shouldn't be empty (use -s) \nexiting...\n" && exit
echo "Script Folder path:    $(pwd)/${SCRIPT_FOLDER_PATH}"

[ -z "$TEST_FOLDER_PATH" ] && printf "Test Folders path shouldn't be empty (use -t) \nexiting...\n" && exit
echo "Test Folders path:     $(pwd)/${TEST_FOLDER_PATH}"

[ -z "$RESULT_DIR_NAME" ] && printf "Result Directory Path shouldn't be empty (use -s) \nexiting...\n" && exit
echo "Result Directory Path: $(pwd)/${RESULT_DIR_NAME}"

echo "Extension:             ${EXTENSION}"
echo "Interpreter:           ${INTERPRETER}"

# delete Result Dir if exists
if [ ! -d "${RESULT_DIR_NAME}" ]; then
    mkdir ${RESULT_DIR_NAME}
fi

echo
echo "Starting Tests..."

compare_files(){
    SCRIPT_PATH=$1
    PTEST_DIR_NAME=$2
    RES_DIR_NAME=$3
    TNUM=$4
    
    FNAME=${SCRIPT_PATH%.*}
    FNAME=${FNAME##*/}
    
    for i in $(seq 1 $TNUM);
    do
        while [ ${#i} -lt 3 ]; do
            i=0$i
        done
        
        CURRENT_TEST=${PTEST_DIR_NAME}${i}.dat
        CURRENT_TEST_ANS=${PTEST_DIR_NAME}${i}.ans
        DEST_FILE_NAME=${RES_DIR_NAME}/${FNAME}_${i}.txt
        
        # launch your python script
        eval ${INTERPRETER} ${SCRIPT_PATH} \"$CURRENT_TEST\" "${DEST_FILE_NAME}"
        
        # check if correct
        echo "Test ${i} : $(eval diff -w -q \"$CURRENT_TEST_ANS\" \"$DEST_FILE_NAME\" && echo "Success: files are same!" || echo "Failed: files are different")"
    done
}

run_test(){
    TNAME="$1"
    PROG_NAME="$2"
    TEST_SUB_FOLD="$3"
    TNUM="$4"
    
    echo
    echo "### Checking ${TNAME}"
    
    SCRIPT=${SCRIPT_FOLDER_PATH}/${PROG_NAME}
    TESTS=${TEST_FOLDER_PATH}/${TEST_SUB_FOLD}/
    RES_DIR=${RESULT_DIR_NAME}/${TEST_SUB_FOLD}/
    
    if [ ! -f "${SCRIPT}" ]; then
        echo "Script not found (Try using -e flag)"
        return
    fi
    
    if [ -d "${RES_DIR}" ]; then
        rm -rf ${RES_DIR}
    fi
    mkdir $RES_DIR
    eval compare_files \"${SCRIPT}\" \"${TESTS}\" \"${RES_DIR}\" "${TNUM}"
}


compare_files1(){
    SCRIPT_PATH=$1
    PTEST_DIR_NAME=$2
    RES_DIR_NAME=$3
    TNUM=$4
    TEST_SCRIPT=$5
    
    FNAME=${SCRIPT_PATH%.*}
    FNAME=${FNAME##*/}
    
    for i in $(seq 1 $TNUM);
    do
        while [ ${#i} -lt 3 ]; do
            i=0$i
        done
        
        CURRENT_TEST=${PTEST_DIR_NAME}${i}.dat
        CURRENT_TEST_ANS=${PTEST_DIR_NAME}${i}.ans
        DEST_FILE_NAME=${RES_DIR_NAME}/${FNAME}_${i}.txt
        
        # launch your python script
        eval ${INTERPRETER} ${SCRIPT_PATH} \"${CURRENT_TEST}\" "${DEST_FILE_NAME}"
        
        # check if correct
        echo "Test ${i}: "
        python3 "${TESTER_SCRIPT_FOLDER}/${TEST_SCRIPT}" "${CURRENT_TEST_ANS}" "${CURRENT_TEST}" "${DEST_FILE_NAME}"
        echo
    done
}

run_test1(){
    TNAME="$1"
    PROG_NAME="$2"
    TEST_SUB_FOLD="$3"
    TNUM="$4"
    TEST_SCRIPT="$5"
    
    echo
    echo "### Checking ${TNAME}"
    
    SCRIPT=${SCRIPT_FOLDER_PATH}/${PROG_NAME}
    TESTS=${TEST_FOLDER_PATH}/${TEST_SUB_FOLD}/
    RES_DIR=${RESULT_DIR_NAME}/${TEST_SUB_FOLD}/
    
    if [ ! -f "${SCRIPT}" ]; then
        echo "Script not found (Try using -e flag)"
        return
    fi
    
    if [ -d "${RES_DIR}" ]; then
        rm -rf ${RES_DIR}
    fi
    mkdir $RES_DIR
    eval compare_files1 \"${SCRIPT}\" \"${TESTS}\" \"${RES_DIR}\" "${TNUM}" ${TEST_SCRIPT}
}


compare_files2(){
    SCRIPT_PATH=$1
    PTEST_DIR_NAME=$2
    RES_DIR_NAME=$3
    TNUM=$4
    
    FNAME=${SCRIPT_PATH%.*}
    FNAME=${FNAME##*/}
    
    for i in $(seq 1 $TNUM);
    do
        while [ ${#i} -lt 3 ]; do
            i=0$i
        done
        
        CURRENT_TEST=${PTEST_DIR_NAME}${i}.dat
        CURRENT_TEST_CODE=${PTEST_DIR_NAME}${i}.code
        CURRENT_TEST_ANS=${PTEST_DIR_NAME}${i}.ans
        DEST_FILE_NAME=${RES_DIR_NAME}/${FNAME}_${i}.txt
        
        # launch your python script
        eval ${INTERPRETER} ${SCRIPT_PATH} \"$CURRENT_TEST_CODE\" \"$CURRENT_TEST\" "${DEST_FILE_NAME}"
        
        # check if correct
        echo "Test ${i} : $(eval diff -w -q \"$CURRENT_TEST_ANS\" \"$DEST_FILE_NAME\" && echo "Success: files are same!" || echo "Failed: files are different")"
    done
}

run_test2(){
    TNAME="$1"
    PROG_NAME="$2"
    TEST_SUB_FOLD="$3"
    TNUM="$4"
    
    echo
    echo "### Checking ${TNAME}"
    
    SCRIPT=${SCRIPT_FOLDER_PATH}/${PROG_NAME}
    TESTS=${TEST_FOLDER_PATH}/${TEST_SUB_FOLD}/
    RES_DIR=${RESULT_DIR_NAME}/${TEST_SUB_FOLD}/
    
    if [ ! -f "${SCRIPT}" ]; then
        echo "Script not found (Try using -e flag)"
        return
    fi
    
    if [ -d "${RES_DIR}" ]; then
        rm -rf ${RES_DIR}
    fi
    mkdir $RES_DIR
    eval compare_files2 \"${SCRIPT}\" \"${TESTS}\" \"${RES_DIR}\" "${TNUM}"
}

run_test1 "StandardForm" "StandardForm${EXTENSION}" "A" 8 "test_A.py"
run_test1 "ParityCheck" "ParityCheck${EXTENSION}" "B" 8 "test_B.py"

run_test2 "Encode" "Encode${EXTENSION}" "D" 6
run_test "Decode" "Decode${EXTENSION}" "E" 6